# Use the official Nginx image
FROM nginx:alpine

# Set the working directory to the Nginx default HTML directory
WORKDIR /usr/share/nginx/html

# Copy the frontend static files into the container
COPY index.html app.js ./

# No need to run any command since Nginx runs by default





