FROM nginx:alpine
# Set the working directory to /usr/share/nginx/html
WORKDIR /usr/share/nginx/html
# Copy the static files from your local frontend directory to the Nginx container
COPY . .
# Expose port 80 to allow access to the server
EXPOSE 80

