# version: '3'
# services:
#   backend:
#     build:
#       context: ./backend
#     container_name: backend
#     ports:
#       - "5000:5000"
#     environment:
#       - REDIS_HOST=redis
#     networks:
#       - app-network
#     depends_on:
#       - redis

#   frontend:
#     build:
#       context: ./frontend
#     container_name: frontend
#     ports:
#       - "3000:3000"
#     networks:
#       - app-network

#   nginx:
#     image: nginx:latest
#     container_name: nginx
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     ports:
#       - "80:80"
#     networks:
#       - app-network
#     depends_on:
#       - frontend
#       - backend

#   redis:
#     image: redis:latest
#     container_name: redis
#     ports:
#       - "6379:6379"
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge
version: '3'

services:
  frontend:
    build:
      context: ./frontend  # Frontend directory
    ports:
      - "8080:80"  # Expose port 8080 for frontend
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend  # Backend directory
    ports:
      - "5000:5000"  # Expose port 5000 for backend
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
