- name: Deploy and Set Up Application on EC2
  hosts: webservers
  become: true 
  vars:
    repo_url: "https://github.com/Yazanzeiden/SimpleDevOpsProject.git"  # Your repository URL
    dest_dir: "/home/ec2-user/SimpleDevOpsProject"  # Destination directory on EC2
    docker_compose_dir: "/home/ec2-user/SimpleDevOpsProject"  # Location of docker-compose.yml
    unit_test_result: True  # Set to 'true' to simulate pass, 'false' to simulate fail

  tasks:
    
    - name: Clone the repository into the home directory
      git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_dir }}"
        version: Master
        force: yes

   
    - name: Run mock unit test
      debug:
        msg: "Unit test result: {{ unit_test_result }}"
      failed_when: unit_test_result == false  # Fail if 'unit_test_result' is false

    
    - name: Rebuild Docker images
      command: docker-compose build
      args:
        chdir: "{{ docker_compose_dir }}"

  
    - name: Stop running Docker Compose services
      command: docker-compose down
      args:
        chdir: "{{ docker_compose_dir }}"

   
    - name: Start Docker Compose services in detached mode
      command: docker-compose up -d
      args:
        chdir: "{{ docker_compose_dir }}"


    
    - name: Check if Docker Compose services are running
      command: docker-compose ps
      args:
        chdir: "{{ docker_compose_dir }}"
      register: docker_compose_status
      failed_when: "'Up' not in docker_compose_status.stdout"

    
    - name: Show success message
      debug:
        msg: "Deployment was successful, Docker Compose is running."

